import React, { useState, useEffect, useRef } from 'react';
import { generateDeepMindAnalysis } from '../services/geminiService';
import { Sparkles, BrainCircuit, Send, User, Quote, Scroll, History, BookOpen, Printer, Download, Share2, Mail, Twitter } from 'lucide-react';

declare global {
    interface Window {
        html2canvas: any;
        jspdf: any;
    }
}

export const ReportAnalyzer: React.FC = () => {
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState<{
    title: string;
    executiveSummary: string;
    strategicSynthesis: string;
    councilVoices: { strategist: string; quote: string; application: string }[];
    conclusion: string;
  } | null>(null);

  const reportContainerRef = useRef<HTMLDivElement>(null);
  const contentRef = useRef<HTMLDivElement>(null);

  const handleAnalyze = async () => {
    if (!query.trim()) return;
    
    setLoading(true);
    setReport(null);
    
    try {
      const result = await generateDeepMindAnalysis(query);
      setReport(result);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (report && reportContainerRef.current) {
        reportContainerRef.current.scrollIntoView({ behavior: 'smooth' });
    }
  }, [report]);

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadPDF = async () => {
    if (!contentRef.current || !window.html2canvas || !window.jspdf) {
        alert("PDF generation libraries not loaded. Please try printing to PDF instead.");
        return;
    }

    try {
        const originalElement = contentRef.current;
        
        // Clone the element to capture full height off-screen
        const clonedElement = originalElement.cloneNode(true) as HTMLElement;
        
        // Apply temporary styles to the clone for optimal capture
        Object.assign(clonedElement.style, {
            position: 'absolute',
            top: '-9999px',
            left: '-9999px',
            width: '1000px', // Fixed width for consistent rendering
            height: 'auto',
            maxHeight: 'none',
            overflow: 'visible',
            zIndex: '-1'
        });
        
        document.body.appendChild(clonedElement);

        const canvas = await window.html2canvas(clonedElement, { 
            scale: 2,
            useCORS: true,
            backgroundColor: '#ffffff',
            windowWidth: 1000
        });
        
        // Clean up
        document.body.removeChild(clonedElement);
        
        const imgData = canvas.toDataURL('image/png');
        const { jsPDF } = window.jspdf;
        const pdf = new jsPDF('p', 'mm', 'a4');
        const pageWidth = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();
        
        const imgProps = pdf.getImageProperties(imgData);
        const pdfHeight = (imgProps.height * pageWidth) / imgProps.width;
        
        let heightLeft = pdfHeight;
        let position = 0;

        // Add first page
        pdf.addImage(imgData, 'PNG', 0, position, pageWidth, pdfHeight);
        heightLeft -= pageHeight;

        // Add subsequent pages if content is long
        while (heightLeft > 0) {
          position -= pageHeight;
          pdf.addPage();
          pdf.addImage(imgData, 'PNG', 0, position, pageWidth, pdfHeight);
          heightLeft -= pageHeight;
        }
        
        pdf.save(`Salus_DeepMind_Analysis_${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
        console.error("PDF generation failed:", error);
        alert("Failed to generate PDF. Please try the Print button.");
    }
  };

  const handleEmailReport = () => {
    if (!report) return;
    const subject = encodeURIComponent(`Salus Intelligence Report: ${report.title}`);
    const body = encodeURIComponent(
        `EXECUTIVE SUMMARY\n${report.executiveSummary}\n\n` +
        `STRATEGIC SYNTHESIS (SITREP)\n${report.strategicSynthesis}\n\n` +
        `CONCLUSION\n${report.conclusion}\n\n` +
        `Generated by Salus Deep Mind Analysis.`
    );
    window.location.href = `mailto:analysis@salusinternational.net?subject=${subject}&body=${body}`;
  };

  const handleShareTwitter = () => {
    if (!report) return;
    const text = encodeURIComponent(`Salus Intel: ${report.title} - ${report.executiveSummary.substring(0, 100)}...`);
    const url = encodeURIComponent(window.location.href);
    window.open(`https://twitter.com/intent/tweet?text=${text}&url=${url}`, '_blank');
  };

  const handleShare = async () => {
    if (navigator.share) {
        try {
            await navigator.share({
                title: report?.title || 'Salus Intelligence Report',
                text: report?.executiveSummary || 'Check out this strategic analysis.',
                url: window.location.href
            });
        } catch (error) {
            console.log('Error sharing:', error);
        }
    } else {
        alert("Sharing not supported on this browser. Copying URL to clipboard.");
        navigator.clipboard.writeText(window.location.href);
    }
  };

  return (
    <div className="h-full flex flex-col gap-6 animate-fade-in pb-10">
      {/* Header */}
      <div className="bg-slate-800 p-8 rounded-xl border border-slate-700 shadow-lg print:hidden">
         <div className="flex items-start gap-4">
            <div className="p-4 bg-purple-600/20 rounded-xl text-purple-400 border border-purple-500/30">
                <BrainCircuit size={32} />
            </div>
            <div>
                <h2 className="text-3xl font-bold text-white mb-2 tracking-tight">SALUS Political Intelligence Processor</h2>
                <p className="text-slate-400 text-lg max-w-3xl">
                    Ask complex questions about Ugandan politics. The system will convene a 
                    <span className="text-purple-400 font-bold"> Council of Historical Strategists </span> 
                    (Sun Tzu, Chanakya, Napoleon, Gandhi, etc.) to synthesize a high-level strategic SitRep.
                </p>
            </div>
         </div>
      </div>

      {/* Input Area */}
      <div className="bg-slate-800 p-6 rounded-xl border border-slate-700 shadow-lg print:hidden">
          <div className="relative">
              <input 
                  type="text" 
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && handleAnalyze()}
                  placeholder="e.g., What is the strategic vulnerability of NUP's youth mobilization? OR How can NRM secure the transition?"
                  className="w-full bg-slate-900 border border-slate-600 rounded-xl py-4 pl-6 pr-16 text-lg text-white placeholder-slate-500 focus:outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-500 transition-all"
                  disabled={loading}
              />
              <button 
                  onClick={handleAnalyze}
                  disabled={!query.trim() || loading}
                  className="absolute right-3 top-1/2 transform -translate-y-1/2 bg-purple-600 hover:bg-purple-500 text-white p-2.5 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                  {loading ? <Sparkles className="animate-spin" size={20} /> : <Send size={20} />}
              </button>
          </div>
          <div className="mt-4 flex flex-wrap gap-2 text-xs text-slate-500 font-medium uppercase tracking-wider">
              <span>Council Members:</span>
              <span className="px-2 py-1 bg-slate-900 rounded border border-slate-800">Sun Tzu</span>
              <span className="px-2 py-1 bg-slate-900 rounded border border-slate-800">Chanakya</span>
              <span className="px-2 py-1 bg-slate-900 rounded border border-slate-800">Napoleon</span>
              <span className="px-2 py-1 bg-slate-900 rounded border border-slate-800">Gandhi</span>
              <span className="px-2 py-1 bg-slate-900 rounded border border-slate-800">Che Guevara</span>
              <span className="px-2 py-1 bg-slate-900 rounded border border-slate-800">Genghis Khan</span>
              <span className="px-2 py-1 bg-slate-900 rounded border border-slate-800">Lincoln</span>
          </div>
      </div>

      {/* Report Area */}
      <div ref={reportContainerRef} className="print:w-full">
          {loading ? (
             <div className="flex flex-col items-center justify-center py-20 text-center space-y-6 bg-slate-800/50 rounded-xl border border-dashed border-slate-700">
                <div className="relative">
                    <div className="w-24 h-24 border-4 border-slate-700 border-t-purple-500 rounded-full animate-spin"></div>
                    <BrainCircuit className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 text-purple-500 animate-pulse" size={40} />
                </div>
                <div>
                   <h3 className="text-2xl font-bold text-white mb-2">Synthesizing Strategic Doctrine...</h3>
                   <p className="text-slate-400 text-lg">Consulting The Art of War, The Arthashastra, and Revolutionary Diaries.</p>
                   <div className="flex justify-center gap-4 mt-8">
                       <span className="text-xs bg-slate-900 px-3 py-1.5 rounded text-slate-500 animate-pulse border border-slate-800">Analyzing Context</span>
                       <span className="text-xs bg-slate-900 px-3 py-1.5 rounded text-slate-500 animate-pulse delay-75 border border-slate-800">Applying Ideologies</span>
                       <span className="text-xs bg-slate-900 px-3 py-1.5 rounded text-slate-500 animate-pulse delay-150 border border-slate-800">Formulating SitRep</span>
                   </div>
                </div>
             </div>
          ) : report ? (
             <div>
                {/* Actions Toolbar */}
                <div className="flex justify-end gap-3 mb-4 print:hidden">
                    <button 
                        onClick={handleEmailReport}
                        className="flex items-center gap-2 px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition-colors text-sm font-medium"
                    >
                        <Mail size={16} /> Email Report
                    </button>
                    <button 
                        onClick={handleShareTwitter}
                        className="flex items-center gap-2 px-4 py-2 bg-[#1DA1F2] hover:bg-[#1a91da] text-white rounded-lg transition-colors text-sm font-medium"
                    >
                        <Twitter size={16} /> Tweet
                    </button>
                    <button 
                        onClick={handleDownloadPDF}
                        className="flex items-center gap-2 px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition-colors text-sm font-medium"
                    >
                        <Download size={16} /> Download SitRep PDF
                    </button>
                    <button 
                        onClick={handlePrint}
                        className="flex items-center gap-2 px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition-colors text-sm font-medium"
                    >
                        <Printer size={16} /> Print
                    </button>
                    <button 
                        onClick={handleShare}
                        className="flex items-center gap-2 px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg transition-colors text-sm font-medium"
                    >
                        <Share2 size={16} /> Share
                    </button>
                </div>

                <div ref={contentRef} id="report-content" className="bg-white text-slate-900 rounded-xl shadow-2xl overflow-hidden border border-slate-200">
                    {/* Report Header */}
                    <div className="bg-[#1e1b4b] text-white p-8 md:p-12 border-b-4 border-purple-600 relative overflow-hidden">
                        <div className="absolute top-0 right-0 p-8 opacity-10">
                            <Scroll size={120} />
                        </div>
                        <div className="relative z-10">
                            <div className="flex items-center gap-3 mb-4 text-purple-300 text-xs font-bold uppercase tracking-[0.2em]">
                                <History size={14} /> 
                                <span>Salus Deep Mind // Strategic Assessment</span>
                            </div>
                            <h1 className="text-3xl md:text-5xl font-bold font-serif leading-tight mb-6">
                                {report.title}
                            </h1>
                            <div className="bg-white/10 backdrop-blur-md p-6 rounded-lg border border-white/10">
                                <h3 className="text-sm font-bold text-purple-300 uppercase mb-2">Executive Summary</h3>
                                <p className="text-white/90 text-lg leading-relaxed font-sans">
                                    {report.executiveSummary}
                                </p>
                            </div>
                        </div>
                    </div>

                    <div className="p-8 md:p-12 bg-[#f8fafc] grid grid-cols-1 lg:grid-cols-12 gap-12">
                        
                        {/* Main Synthesis Column */}
                        <div className="lg:col-span-7 space-y-10">
                            <div>
                                <h3 className="flex items-center gap-3 text-xl font-bold text-[#1e1b4b] mb-6 border-b border-slate-300 pb-3">
                                    <BookOpen className="text-purple-600" /> Strategic Synthesis (SitRep)
                                </h3>
                                <div className="prose prose-lg text-slate-700 leading-8 font-serif">
                                    <p className="whitespace-pre-line">
                                        {report.strategicSynthesis}
                                    </p>
                                </div>
                            </div>

                            <div className="bg-purple-50 p-8 rounded-xl border border-purple-100">
                                <h3 className="flex items-center gap-3 text-lg font-bold text-purple-900 mb-4">
                                    <Sparkles size={20} className="text-purple-600" /> Final Strategic Verdict
                                </h3>
                                <p className="text-purple-800 text-lg font-medium italic leading-relaxed">
                                    "{report.conclusion}"
                                </p>
                            </div>
                        </div>

                        {/* Council Voices Column */}
                        <div className="lg:col-span-5 space-y-6">
                            <h3 className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-2">
                                Voices from the Council
                            </h3>
                            
                            {report.councilVoices.map((voice, idx) => (
                                <div key={idx} className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 hover:shadow-md transition-shadow relative group break-inside-avoid">
                                    <div className="absolute -left-1 top-6 w-1 h-12 bg-purple-600 rounded-r opacity-0 group-hover:opacity-100 transition-opacity"></div>
                                    <div className="flex items-center gap-2 mb-3">
                                        <User size={16} className="text-slate-400" />
                                        <span className="text-sm font-bold text-slate-900 uppercase">{voice.strategist}</span>
                                    </div>
                                    <div className="mb-4">
                                        <Quote size={20} className="text-purple-300 mb-2" />
                                        <p className="text-slate-600 italic font-serif text-lg leading-snug">
                                            "{voice.quote}"
                                        </p>
                                    </div>
                                    <div className="bg-slate-50 p-3 rounded text-sm text-slate-700 border border-slate-100">
                                        <span className="font-bold text-purple-700 text-xs uppercase block mb-1">Application</span>
                                        {voice.application}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    <div className="bg-slate-100 p-4 text-center border-t border-slate-200 text-slate-500 text-xs font-mono uppercase">
                        Generated by Salus Deep Mind • {new Date().toLocaleDateString()}
                    </div>
                </div>
             </div>
          ) : (
             <div className="h-64 flex flex-col items-center justify-center text-slate-600 border-2 border-dashed border-slate-700/50 rounded-xl bg-slate-800/30">
                 <Scroll size={48} className="mb-4 opacity-20" />
                 <p className="text-lg font-medium text-slate-500">Awaiting Query...</p>
                 <p className="text-sm text-slate-600">Enter a question above to convene the Council.</p>
             </div>
          )}
      </div>
    </div>
  );
};